const getServerById = 'SELECT * FROM servers WHERE server_id = $1;'; // last 10 requests object is added in server-controller.
const getAllServers = 'SELECT * FROM servers;';
const createServer = 'INSERT INTO servers (http_url, name, is_healthy) VALUES ($1, $2, $3) RETURNING *;';
const deleteServerById = 'DELETE FROM servers WHERE server_id = $1 RETURNING *;';
// updateServerById - Generated by function in '../helpers/database.js'

module.exports = {
  getServerById,
  getAllServers,
  createServer,
  deleteServerById,
};
